tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up -d
      docker ps

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
