services:
  express:
    image: node
    ports:
      - "8000:8000"
    command: ["CMD", "npm", "i", "express", "&", "npm", "i", "body-parser", "&", "node", "https://raw.githubusercontent.com/zeldalegends/tutorials.PEP-Proxy/custom-aio/express-app/server.js"]
